version: '3.9'

name: vectoradmin

networks:
  vector-admin:
    driver: bridge

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vectoradmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vdbms
    networks:
      - vector-admin
  vector-admin:
    container_name: vector-admin
    image: vector-admin:latest
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    volumes:
      - "./.env:/app/backend/.env"
      - "../backend/storage:/app/backend/storage"
      - "../document-processor/hotdir/:/app/document-processor/hotdir"
    ports:
      - "3001:3001"
      - "3355:3355"
      - "8288:8288"
    env_file:
      - .env
    networks:
      - vector-admin
    depends_on:
      - postgres
